server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  devtools:
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
