server:
  port: 8080

spring:
  devtools:
    livereload:
      port: 35730

  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
#    database-platform: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
    username: iu
    password: iu1004
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy